---
- name: Enable required cgroup features and disable IPv6
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory ipv6.disable=1)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory ipv6.disable=1'
    state: present

- name: Set Pi-Hat fan speed to turn on when CPU temp is 65C, turn off at 60C
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE POE FAN SPEED -->"
    block: |
      dtparam=poe_fan_temp0=60000,poe_fan_temp0_hyst=5000
      dtparam=poe_fan_temp1=65000,poe_fan_temp1_hyst=2000
  
- name: Disable WiFi
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE WIFI -->"
    block: |
      dtoverlay=pi3-disable-wifi
  
- name: Disable Bluetooth
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE BLUETOOTH -->"
    block: |
      dtoverlay=pi3-disable-bt

- name: Disable HDMI
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE HDMI -->"
    block: |
      hdmi_blanking=2

- name: Disable Audio
  lineinfile:
    path: /boot/config.txt
    regexp: '^dtparam=audio=on$'
    line: 'dtparam=audio=off'
    state: present
