---
- name: Enable required cgroup features and disable IPv6
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_enable=cpuset cgroup_enable=memory ipv6.disable=1)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory ipv6.disable=1'
    state: present

- name: Check if Pi-Hat fan speed already adjusted
  shell: grep "^poe_fan_temp0" /boot/config.txt
  register: fan_speed_enabled

- name: Set Pi-Hat fan speed to turn on when CPU temp is 80C, turn off at 75C
  blockinfile:
    path: /boot/config.txt
    block: |
      dtparam=poe_fan_temp0=80000,poe_fan_temp0_hyst=5000
      dtparam=poe_fan_temp1=82000,poe_fan_temp1_hyst=2000
  when: fan_speed_enabled.stdout != ""
  
  
