---
- name: Enable required cgroup features and disable IPv6
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: True
    regexp: '^(.*rootwait)$'
    line: '\1 ipv6.disable=1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    state: present
  
- name: Disable WiFi
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE WIFI"
    block: |
      dtoverlay=pi3-disable-wifi
  
- name: Disable Bluetooth
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE BLUETOOTH"
    block: |
      dtoverlay=pi3-disable-bt

- name: Disable HDMI
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE HDMI"
    block: |
      hdmi_blanking=2

- name: Disable Audio
  lineinfile:
    path: /boot/config.txt
    regexp: '^dtparam=audio=(on|off)$'
    line: 'dtparam=audio=off'
    state: present
    
- name: Set GPU memory to 16M
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE GPU MEM"
    block: |
      gpu_mem=16
