---

- name: Install Neofetch
  apt:
    name:
      - neofetch
    update_cache: yes
    # Need the force_apt_get until
    # https://github.com/ansible/ansible/issues/56832
    force_apt_get: yes

- name: Enable neofetch on login
  copy:
    content: "neofetch"
    dest: "/home/{{ ansible_ssh_user }}/.bash_profile"
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    mode: 0775

- name: Quite the login prompt
  file:
    dest: "/home/{{ ansible_ssh_user }}/.hushlogin"
    state: touch
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    mode: 0775

- name: Remove motd
  command: update-rc.d motd remove

- name: Create config directory
  file:
    path: "/home/{{ ansible_ssh_user }}/.config"
    state: directory
    recurse: yes
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    mode: 0775

- name: Create neofetch directory
  file:
    path: "/home/{{ ansible_ssh_user }}/.config/neofetch"
    state: directory
    recurse: yes
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    mode: 0775

- name: Add custom neofetch config
  template:
    src: "templates/neofetch.conf.j2"
    dest: "/home/{{ ansible_ssh_user }}/.config/neofetch/config.conf"
    group: "{{ ansible_ssh_user }}"
    owner: "{{ ansible_ssh_user }}"
    mode: 0775